using System;
using System.ComponentModel.DataAnnotations;

namespace Backend.Models
{
    /// <summary>
    /// Patient Record Model
    /// </summary>
    public class Patient
    {
        // Autogenerated Patient ID
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        [DataType(DataType.Date)]
        public DateTime Birthday { get; set; }
        public Gender Gender { get; set; }
    }
}

/// <summary>
/// Patient Gender Enum
/// </summary>
public enum Gender
{
    Male,
    Female
}